In [1]:
import gym # pip install gym
import numpy as np
import time
from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
env.render()


SFFF
FHFH
FFFH
HFFG


In [4]:
numActions = env.action_space.n
numStates = env.observation_space.n

In [5]:
print(numActions,numStates)

4 16


In [6]:
Q = np.zeros((numStates,numActions))

In [7]:
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
nE = 1000
mpE = 100
alpha = 0.25
gamma = 0.99
epsilon = 1
edr = 0.00001

In [9]:
for e in range(nE):
    state = env.reset()
    done = False
    for step in range(mpE):
        if np.random.rand() > epsilon:
            action = np.argmax(Q[state,:])
        else:
            action = env.action_space.sample()
        ns,reward,done,info = env.step(action)
        Q[state,action] = (1-alpha)*Q[state,action]+alpha*(
        reward+gamma*np.max(Q[ns,:]))
        state = ns
        if done == True:
            break
    epsilon = epsilon*np.exp(-edr*e)
    alpha = alpha*np.exp(-edr*e)
    
        

In [10]:
Q

array([[0.37071906, 0.29781034, 0.30783272, 0.30372954],
       [0.11989631, 0.0811449 , 0.07318645, 0.27117805],
       [0.21372349, 0.0834144 , 0.09053864, 0.09043132],
       [0.01954035, 0.02205058, 0.01688234, 0.08439756],
       [0.38334002, 0.2401247 , 0.23382544, 0.20271248],
       [0.        , 0.        , 0.        , 0.        ],
       [0.19297669, 0.03972127, 0.08812737, 0.04763932],
       [0.        , 0.        , 0.        , 0.        ],
       [0.21747757, 0.23471289, 0.23300025, 0.41172024],
       [0.19267835, 0.45568108, 0.22146905, 0.17946966],
       [0.44031075, 0.15965094, 0.15128309, 0.08161276],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.18891998, 0.24707926, 0.54678339, 0.29630544],
       [0.33371486, 0.48576556, 0.59917244, 0.6534683 ],
       [0.        , 0.        , 0.        , 0.        ]])

In [11]:
for e in range(5):
    state = env.reset()
    done = False
    print("Episode::",e)
    time.sleep(0.1)
    for step in range(mpE):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(Q[state,:])
        ns,reward,done,info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("Goal")
                time.sleep(3)
            else:
                print("Hole")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = ns
env.close()
            
            

  (Up)
SFFF
FHFH
FFFH
HFFG
Hole
